# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets/dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/select2/dist/css"
    - "node_modules/flatpickr/dist"
  # Paths to file entry points for webpack/gulp-sass to bundle files
  entries:
    scss:
      - "assets/src/scss/admin/rbm-field-helpers-admin.scss"
      - "assets/src/scss/admin/rbm-fh-select2.scss"
    js: 
      - "assets/src/js/admin/rbm-field-helpers-admin.js"
  licenses:
    - "node_modules/select2/LICENSE.md"
    - "node_modules/jquery.repeater/LICENSE.md"
    - "node_modules/flatpickr/LICENSE.md"